# Generated by Django 4.1 on 2023-05-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babadu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarangWishlist',
            new_name='Member',
        ),
    ]
