# Generated by Django 4.1 on 2023-05-07 02:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('babadu', '0003_remove_member_userid_member_is_atlet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AlterField(
            model_name='atlet',
            name='jenis_kelamin',
            field=models.BooleanField(choices=[(True, 'Putra'), (False, 'Putri')]),
        ),
        migrations.AlterField(
            model_name='atlet',
            name='play_right',
            field=models.BooleanField(choices=[(True, 'Right'), (False, 'Left')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
