# Generated by Django 4.1 on 2023-05-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babadu', '0004_remove_member_user_alter_atlet_jenis_kelamin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelatih',
            name='kategori',
            field=models.CharField(default='Tunggal Putra', max_length=50),
        ),
        migrations.AddField(
            model_name='pelatih',
            name='negara',
            field=models.CharField(default='Indonesia', max_length=50),
        ),
    ]
