# Generated by Django 4.1 on 2023-05-07 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('babadu', '0005_pelatih_kategori_pelatih_negara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spesialisasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kategori', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='pelatih',
            name='kategori',
        ),
        migrations.AddField(
            model_name='pelatih',
            name='kategori',
            field=models.ManyToManyField(to='babadu.spesialisasi'),
        ),
    ]
